### ISSUE TITLE
각 구들의 좌표코드 

### ISSUE THREAD

**Issue by okeyeyo** [underkim/summer_project#18]
<img src="광주.png" usemap="#image-map">

<map name="image-map">

    <area target="" alt="동구" title="동구" href="" coords="585,329,593,323,595,319,599,315,601,310,605,305,606,299,617,301,619,308,624,311,629,310,636,304,639,305,643,310,646,310,651,313,659,313,662,321,665,324,674,325,680,329,680,333,677,337,678,343,673,347,675,352,684,359,696,359,706,367,711,369,716,366,731,365,739,367,743,374,745,379,748,388,752,393,757,401,763,402,775,406,781,407,776,413,771,418,771,423,758,429,752,431,750,438,746,440,745,448,749,453,747,460,750,471,745,473,741,472,734,477,720,478,715,483,707,484,699,488,689,499,688,503,690,510,686,512,682,516,677,524,670,527,660,524,654,525,648,522,636,522,636,513,629,509,623,504,622,496,619,486,612,478,612,465,607,459,607,451,599,443,599,436,597,434,597,426,597,419,607,418,613,411,620,401,630,395,632,388,629,383,625,382,622,375,619,371,613,366,613,361,608,356,606,351,601,345,596,341,593,335" shape="poly">

    <area target="" alt="남구" title="남구" href="" coords="589,337,579,337,573,334,569,328,562,328,556,334,544,337,540,341,544,350,536,361,542,372,542,381,542,387,545,394,545,412,535,418,530,418,515,410,506,419,510,424,505,433,498,433,495,436,489,435,486,443,476,442,467,444,462,444,457,447,454,447,450,454,444,455,435,463,426,464,421,470,415,476,407,478,402,482,396,475,392,475,387,480,380,479,374,468,369,474,366,482,357,488,352,494,350,499,346,504,342,510,335,521,327,530,316,532,308,532,298,536,288,538,275,538,267,540,265,546,268,550,269,556,271,558,275,552,280,548,291,547,294,551,295,557,293,564,295,570,303,574,310,575,316,572,325,571,336,560,346,556,350,552,354,558,361,558,367,567,368,574,374,580,383,574,397,575,405,555,415,552,423,551,427,548,433,548,436,541,451,543,456,533,460,526,469,524,475,511,481,511,485,508,489,516,497,517,505,521,513,519,520,513,526,510,535,504,550,512,557,505,573,505,578,502,580,497,585,493,588,486,595,483,601,479,608,478,609,471,609,464,603,460,603,452,596,444,595,438,593,434,594,424,593,419,597,416,605,416,614,405,619,397,627,394,629,388,623,384,618,374,609,367,609,361,603,353,595,345" shape="poly">

    <area target="" alt="서구" title="서구" href="" coords="571,326,562,325,555,332,544,335,538,340,541,350,534,360,540,373,540,385,543,396,542,411,533,416,515,407,504,418,506,424,506,428,503,431,498,430,494,434,487,433,484,441,475,440,467,442,462,442,456,445,451,445,448,452,443,453,434,461,425,462,414,474,405,476,402,479,397,473,390,473,386,477,383,477,378,471,376,464,368,472,367,468,365,466,365,459,367,455,373,454,376,451,374,446,374,439,371,434,370,429,381,428,385,418,397,419,400,415,399,405,408,398,409,390,403,382,404,376,411,371,417,364,425,357,423,332,416,323,416,315,420,309,414,298,418,291,427,285,438,285,441,276,442,269,444,266,482,277,493,279,505,279,514,281,529,283,534,285,538,290,542,304,545,309,554,308,560,312,565,313,568,319,576,323,581,327,583,330,585,335,576,333" shape="poly">

    <area target="" alt="북구" title="북구" href="" coords="444,262,487,276,506,277,518,280,531,281,537,285,540,290,545,306,555,305,560,310,566,311,569,317,576,321,583,326,591,322,594,315,595,315,599,308,603,304,605,297,618,299,620,305,624,308,628,307,635,302,640,303,644,308,648,308,652,311,660,311,664,319,666,322,675,323,683,329,682,334,680,337,680,344,676,348,685,357,696,357,709,366,719,362,727,362,735,363,741,366,745,373,749,382,750,388,755,393,758,399,764,400,781,406,787,398,793,398,796,391,793,383,790,375,792,356,788,349,788,340,792,334,789,324,789,318,797,307,793,299,796,291,804,291,809,287,810,274,803,266,800,258,795,254,784,245,774,236,766,237,764,243,754,244,749,238,744,238,743,244,740,250,728,245,719,246,718,256,714,261,708,256,704,248,690,235,687,223,694,216,703,204,700,199,695,200,691,195,685,191,671,171,667,159,670,151,676,146,671,142,666,132,658,131,655,120,645,112,633,106,636,88,629,78,619,76,611,75,604,68,596,63,577,62,570,72,552,83,550,90,536,92,524,89,522,80,515,84,505,92,496,93,489,99,489,105,477,111,470,112,465,117,461,119,455,114,454,120,445,125,446,131,436,134,441,143,455,142,461,150,470,149,473,152,474,159,479,162,479,166,474,171,473,177,475,183,477,191,477,202,474,210,472,213,479,216,486,220,488,225,486,231,487,240,487,246,480,252,472,253,466,259,460,260,454,255,448,255" shape="poly">

    <area target="" alt="광산구" title="광산구" href="" coords="413,132,415,130,423,133,429,138,434,136,440,146,453,145,460,153,467,151,470,153,471,161,477,164,471,171,471,177,474,189,474,204,469,213,471,217,478,218,485,224,483,231,485,244,479,250,470,251,465,257,460,257,454,252,447,252,439,267,438,276,435,282,427,282,421,285,412,293,411,300,416,311,412,317,413,324,420,333,422,356,414,363,409,369,401,374,400,382,404,389,406,396,397,404,396,416,382,415,379,426,368,427,368,437,372,442,373,451,365,453,361,460,362,467,365,473,365,480,353,487,348,498,343,504,338,512,332,521,324,528,309,530,301,532,301,526,296,523,292,516,289,512,292,503,289,498,286,496,283,489,283,481,277,478,269,479,264,469,256,458,256,452,250,451,244,444,229,435,224,427,219,423,216,429,216,437,206,435,195,436,188,430,172,433,165,425,157,426,154,433,148,437,143,432,140,434,135,428,131,428,127,425,119,426,118,430,121,437,114,438,103,443,98,444,88,443,91,437,92,426,85,424,79,419,67,423,64,419,64,413,55,408,57,398,56,394,59,391,59,382,63,366,59,360,58,346,46,346,43,340,51,340,54,336,55,331,59,328,60,323,56,319,62,312,64,306,59,302,63,295,65,291,72,291,76,292,81,287,90,284,98,279,98,271,95,268,89,267,79,256,78,245,69,240,60,227,64,223,69,227,75,224,80,227,86,226,96,224,101,230,107,232,111,223,108,215,111,209,110,202,116,197,116,188,121,187,125,182,125,176,129,171,136,171,137,177,156,188,163,188,166,182,171,184,176,178,191,179,193,171,199,166,199,157,194,151,197,145,197,140,206,135,206,126,209,122,211,118,218,112,219,98,234,75,240,79,248,78,257,74,259,67,268,66,275,62,283,65,285,71,279,77,279,87,267,100,266,117,272,123,281,123,286,125,292,127,299,125,303,130,311,132,318,142,330,149,337,147,350,157,362,159,368,155,370,161,375,161,387,154,387,150,394,148,400,148,405,143,414,142" shape="poly">
</map>

**Comment by underkim** [comment]
이미지 사이즈 변화에 따른 수정있음
