### ISSUE TITLE
Main title

### ISSUE THREAD

**Issue by jwjung1108** [underkim/summer_project#7]
홈페이지 첫 화면
- 각 페이지 이동 기능 구현
- 큰 지도 화면에 표시 후 각 구역 세분화
----------------------------------------------
- 추가할 것

**Comment by okeyeyo** [comment]
괜찮다고 생각한 템플릿 목록


[https://ko.wix.com/website-template/view/html/2789?originUrl=https%3A%2F%2Fko.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Fadvertising-marketing%2F2&tpClick=view_button&esi=d8b84ace-fba7-4360-93e5-e060faf4528e](url)

[https://ko.wix.com/website-template/view/html/1322?originUrl=https%3A%2F%2Fko.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Fadvertising-marketing&tpClick=view_button&esi=212ded76-0201-4ec8-9879-f1cf21f966a0](url)

**Comment by jwjung1108** [comment]
정동 수완지구점, 남쪽마을 돌짜장, 송산유원지
ad: " 광주 북구 양일로305번길 26 ",
		st: " 버스 : 일곡사거리 하차",
		ti: " 11:00 ~ 21:30, 브레이크타임 15:00 ~ 16:30",
		pa: " 일곡공용주차장 - 주말무료 ",
		de: " 일요일에는 재료 공급을 위해 오후 4시부터 영업합니다! ",

ad: 
st: 
ti: 
pa: 
de: 


- 어등뼈해장국보쌈
ad: "전라남도 광주광역시 광산구 우산동 무진대로231번길"
st: "버스 : 광산우산동행정복지센터 하차"
ti: "24시간영업"
pa: "빛고을국민체육센터 옆 공영주차장 - 24시간영업"
de: "매일 24시간 영업합니다"

- 정동 수완지구점
ad: "광주광역시 광산구 정동 수완로74번길 11-68 1층"
st: "버스 : 은빛마을 하차"
ti: "11:00 ~ 20:30, 브레이크타임 15:00 ~ 16:30"
pa: "롯데쇼핑(주) 롯데마트수완점 주차장"
de: "브레이크타임과 웨이팅이 길기 때문에 일찍오시는걸 권장드립니다."

- 남쪽마을 돌짜장
ad: "광주광역시 광산구 진곡동 339-13"
st: "버스 : 진성 하차"
ti: "11:00 ~ 18:00"
pa: "주차장 x 주변 인근에 주차"
de: "주차자리가 협소하여 주의 바랍니다."

- 기아 챔피언스 필드
ad: "광주광역시 북구 서림로 10"
st: "버스 : 무등 야구장"
ti: "평균 18:00 ~ 00:00 - 월요일 휴무"
pa: "임동공영주차장"
de: "경기 일정을 참고하여 예매 부탁합니다."

- 송산유원지
ad: "광주광역시 광산구 송산동 195"
st: "버스 : 송산유원지 하차"
ti: "24시간 개방"
pa: "주차장x 주변 인근에 주차"
de: "주차자리가 협소하여 주의 바랍니다."


35.159816, 126.736009
